//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CottageWars.DatabaseServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="MySuperAwesomeService", ConfigurationName="DatabaseServiceReference.DatabaseManagerServiceSoap")]
    public interface DatabaseManagerServiceSoap {
        
        // CODEGEN: Generating message contract since element name userEmail from namespace MySuperAwesomeService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="MySuperAwesomeService/checkForUserE", ReplyAction="*")]
        CottageWars.DatabaseServiceReference.checkForUserEResponse checkForUserE(CottageWars.DatabaseServiceReference.checkForUserERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="MySuperAwesomeService/checkForUserE", ReplyAction="*")]
        System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.checkForUserEResponse> checkForUserEAsync(CottageWars.DatabaseServiceReference.checkForUserERequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace MySuperAwesomeService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="MySuperAwesomeService/checkForUserUP", ReplyAction="*")]
        CottageWars.DatabaseServiceReference.checkForUserUPResponse checkForUserUP(CottageWars.DatabaseServiceReference.checkForUserUPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="MySuperAwesomeService/checkForUserUP", ReplyAction="*")]
        System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.checkForUserUPResponse> checkForUserUPAsync(CottageWars.DatabaseServiceReference.checkForUserUPRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace MySuperAwesomeService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="MySuperAwesomeService/registerUser", ReplyAction="*")]
        CottageWars.DatabaseServiceReference.registerUserResponse registerUser(CottageWars.DatabaseServiceReference.registerUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="MySuperAwesomeService/registerUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.registerUserResponse> registerUserAsync(CottageWars.DatabaseServiceReference.registerUserRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace MySuperAwesomeService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="MySuperAwesomeService/updateBuilding", ReplyAction="*")]
        CottageWars.DatabaseServiceReference.updateBuildingResponse updateBuilding(CottageWars.DatabaseServiceReference.updateBuildingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="MySuperAwesomeService/updateBuilding", ReplyAction="*")]
        System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.updateBuildingResponse> updateBuildingAsync(CottageWars.DatabaseServiceReference.updateBuildingRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace MySuperAwesomeService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="MySuperAwesomeService/buildUnits", ReplyAction="*")]
        CottageWars.DatabaseServiceReference.buildUnitsResponse buildUnits(CottageWars.DatabaseServiceReference.buildUnitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="MySuperAwesomeService/buildUnits", ReplyAction="*")]
        System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.buildUnitsResponse> buildUnitsAsync(CottageWars.DatabaseServiceReference.buildUnitsRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace MySuperAwesomeService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="MySuperAwesomeService/getUnits", ReplyAction="*")]
        CottageWars.DatabaseServiceReference.getUnitsResponse getUnits(CottageWars.DatabaseServiceReference.getUnitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="MySuperAwesomeService/getUnits", ReplyAction="*")]
        System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.getUnitsResponse> getUnitsAsync(CottageWars.DatabaseServiceReference.getUnitsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkForUserERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkForUserE", Namespace="MySuperAwesomeService", Order=0)]
        public CottageWars.DatabaseServiceReference.checkForUserERequestBody Body;
        
        public checkForUserERequest() {
        }
        
        public checkForUserERequest(CottageWars.DatabaseServiceReference.checkForUserERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="MySuperAwesomeService")]
    public partial class checkForUserERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userEmail;
        
        public checkForUserERequestBody() {
        }
        
        public checkForUserERequestBody(string userEmail) {
            this.userEmail = userEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkForUserEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkForUserEResponse", Namespace="MySuperAwesomeService", Order=0)]
        public CottageWars.DatabaseServiceReference.checkForUserEResponseBody Body;
        
        public checkForUserEResponse() {
        }
        
        public checkForUserEResponse(CottageWars.DatabaseServiceReference.checkForUserEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="MySuperAwesomeService")]
    public partial class checkForUserEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool checkForUserEResult;
        
        public checkForUserEResponseBody() {
        }
        
        public checkForUserEResponseBody(bool checkForUserEResult) {
            this.checkForUserEResult = checkForUserEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkForUserUPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkForUserUP", Namespace="MySuperAwesomeService", Order=0)]
        public CottageWars.DatabaseServiceReference.checkForUserUPRequestBody Body;
        
        public checkForUserUPRequest() {
        }
        
        public checkForUserUPRequest(CottageWars.DatabaseServiceReference.checkForUserUPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="MySuperAwesomeService")]
    public partial class checkForUserUPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public checkForUserUPRequestBody() {
        }
        
        public checkForUserUPRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkForUserUPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkForUserUPResponse", Namespace="MySuperAwesomeService", Order=0)]
        public CottageWars.DatabaseServiceReference.checkForUserUPResponseBody Body;
        
        public checkForUserUPResponse() {
        }
        
        public checkForUserUPResponse(CottageWars.DatabaseServiceReference.checkForUserUPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="MySuperAwesomeService")]
    public partial class checkForUserUPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool checkForUserUPResult;
        
        public checkForUserUPResponseBody() {
        }
        
        public checkForUserUPResponseBody(bool checkForUserUPResult) {
            this.checkForUserUPResult = checkForUserUPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerUser", Namespace="MySuperAwesomeService", Order=0)]
        public CottageWars.DatabaseServiceReference.registerUserRequestBody Body;
        
        public registerUserRequest() {
        }
        
        public registerUserRequest(CottageWars.DatabaseServiceReference.registerUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="MySuperAwesomeService")]
    public partial class registerUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        public registerUserRequestBody() {
        }
        
        public registerUserRequestBody(string username, string password, string email) {
            this.username = username;
            this.password = password;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerUserResponse", Namespace="MySuperAwesomeService", Order=0)]
        public CottageWars.DatabaseServiceReference.registerUserResponseBody Body;
        
        public registerUserResponse() {
        }
        
        public registerUserResponse(CottageWars.DatabaseServiceReference.registerUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="MySuperAwesomeService")]
    public partial class registerUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool registerUserResult;
        
        public registerUserResponseBody() {
        }
        
        public registerUserResponseBody(bool registerUserResult) {
            this.registerUserResult = registerUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateBuildingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateBuilding", Namespace="MySuperAwesomeService", Order=0)]
        public CottageWars.DatabaseServiceReference.updateBuildingRequestBody Body;
        
        public updateBuildingRequest() {
        }
        
        public updateBuildingRequest(CottageWars.DatabaseServiceReference.updateBuildingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="MySuperAwesomeService")]
    public partial class updateBuildingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string building;
        
        public updateBuildingRequestBody() {
        }
        
        public updateBuildingRequestBody(string username, string building) {
            this.username = username;
            this.building = building;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateBuildingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateBuildingResponse", Namespace="MySuperAwesomeService", Order=0)]
        public CottageWars.DatabaseServiceReference.updateBuildingResponseBody Body;
        
        public updateBuildingResponse() {
        }
        
        public updateBuildingResponse(CottageWars.DatabaseServiceReference.updateBuildingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="MySuperAwesomeService")]
    public partial class updateBuildingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool updateBuildingResult;
        
        public updateBuildingResponseBody() {
        }
        
        public updateBuildingResponseBody(bool updateBuildingResult) {
            this.updateBuildingResult = updateBuildingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buildUnitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buildUnits", Namespace="MySuperAwesomeService", Order=0)]
        public CottageWars.DatabaseServiceReference.buildUnitsRequestBody Body;
        
        public buildUnitsRequest() {
        }
        
        public buildUnitsRequest(CottageWars.DatabaseServiceReference.buildUnitsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="MySuperAwesomeService")]
    public partial class buildUnitsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int gladiator;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int brute;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int infatry;
        
        public buildUnitsRequestBody() {
        }
        
        public buildUnitsRequestBody(string username, int gladiator, int brute, int infatry) {
            this.username = username;
            this.gladiator = gladiator;
            this.brute = brute;
            this.infatry = infatry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buildUnitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buildUnitsResponse", Namespace="MySuperAwesomeService", Order=0)]
        public CottageWars.DatabaseServiceReference.buildUnitsResponseBody Body;
        
        public buildUnitsResponse() {
        }
        
        public buildUnitsResponse(CottageWars.DatabaseServiceReference.buildUnitsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="MySuperAwesomeService")]
    public partial class buildUnitsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool buildUnitsResult;
        
        public buildUnitsResponseBody() {
        }
        
        public buildUnitsResponseBody(bool buildUnitsResult) {
            this.buildUnitsResult = buildUnitsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUnitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUnits", Namespace="MySuperAwesomeService", Order=0)]
        public CottageWars.DatabaseServiceReference.getUnitsRequestBody Body;
        
        public getUnitsRequest() {
        }
        
        public getUnitsRequest(CottageWars.DatabaseServiceReference.getUnitsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="MySuperAwesomeService")]
    public partial class getUnitsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        public getUnitsRequestBody() {
        }
        
        public getUnitsRequestBody(string Username) {
            this.Username = Username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUnitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUnitsResponse", Namespace="MySuperAwesomeService", Order=0)]
        public CottageWars.DatabaseServiceReference.getUnitsResponseBody Body;
        
        public getUnitsResponse() {
        }
        
        public getUnitsResponse(CottageWars.DatabaseServiceReference.getUnitsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="MySuperAwesomeService")]
    public partial class getUnitsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool getUnitsResult;
        
        public getUnitsResponseBody() {
        }
        
        public getUnitsResponseBody(bool getUnitsResult) {
            this.getUnitsResult = getUnitsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DatabaseManagerServiceSoapChannel : CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatabaseManagerServiceSoapClient : System.ServiceModel.ClientBase<CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap>, CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap {
        
        public DatabaseManagerServiceSoapClient() {
        }
        
        public DatabaseManagerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabaseManagerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseManagerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseManagerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CottageWars.DatabaseServiceReference.checkForUserEResponse CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap.checkForUserE(CottageWars.DatabaseServiceReference.checkForUserERequest request) {
            return base.Channel.checkForUserE(request);
        }
        
        public bool checkForUserE(string userEmail) {
            CottageWars.DatabaseServiceReference.checkForUserERequest inValue = new CottageWars.DatabaseServiceReference.checkForUserERequest();
            inValue.Body = new CottageWars.DatabaseServiceReference.checkForUserERequestBody();
            inValue.Body.userEmail = userEmail;
            CottageWars.DatabaseServiceReference.checkForUserEResponse retVal = ((CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap)(this)).checkForUserE(inValue);
            return retVal.Body.checkForUserEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.checkForUserEResponse> CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap.checkForUserEAsync(CottageWars.DatabaseServiceReference.checkForUserERequest request) {
            return base.Channel.checkForUserEAsync(request);
        }
        
        public System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.checkForUserEResponse> checkForUserEAsync(string userEmail) {
            CottageWars.DatabaseServiceReference.checkForUserERequest inValue = new CottageWars.DatabaseServiceReference.checkForUserERequest();
            inValue.Body = new CottageWars.DatabaseServiceReference.checkForUserERequestBody();
            inValue.Body.userEmail = userEmail;
            return ((CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap)(this)).checkForUserEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CottageWars.DatabaseServiceReference.checkForUserUPResponse CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap.checkForUserUP(CottageWars.DatabaseServiceReference.checkForUserUPRequest request) {
            return base.Channel.checkForUserUP(request);
        }
        
        public bool checkForUserUP(string username, string password) {
            CottageWars.DatabaseServiceReference.checkForUserUPRequest inValue = new CottageWars.DatabaseServiceReference.checkForUserUPRequest();
            inValue.Body = new CottageWars.DatabaseServiceReference.checkForUserUPRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            CottageWars.DatabaseServiceReference.checkForUserUPResponse retVal = ((CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap)(this)).checkForUserUP(inValue);
            return retVal.Body.checkForUserUPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.checkForUserUPResponse> CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap.checkForUserUPAsync(CottageWars.DatabaseServiceReference.checkForUserUPRequest request) {
            return base.Channel.checkForUserUPAsync(request);
        }
        
        public System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.checkForUserUPResponse> checkForUserUPAsync(string username, string password) {
            CottageWars.DatabaseServiceReference.checkForUserUPRequest inValue = new CottageWars.DatabaseServiceReference.checkForUserUPRequest();
            inValue.Body = new CottageWars.DatabaseServiceReference.checkForUserUPRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap)(this)).checkForUserUPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CottageWars.DatabaseServiceReference.registerUserResponse CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap.registerUser(CottageWars.DatabaseServiceReference.registerUserRequest request) {
            return base.Channel.registerUser(request);
        }
        
        public bool registerUser(string username, string password, string email) {
            CottageWars.DatabaseServiceReference.registerUserRequest inValue = new CottageWars.DatabaseServiceReference.registerUserRequest();
            inValue.Body = new CottageWars.DatabaseServiceReference.registerUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.email = email;
            CottageWars.DatabaseServiceReference.registerUserResponse retVal = ((CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap)(this)).registerUser(inValue);
            return retVal.Body.registerUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.registerUserResponse> CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap.registerUserAsync(CottageWars.DatabaseServiceReference.registerUserRequest request) {
            return base.Channel.registerUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.registerUserResponse> registerUserAsync(string username, string password, string email) {
            CottageWars.DatabaseServiceReference.registerUserRequest inValue = new CottageWars.DatabaseServiceReference.registerUserRequest();
            inValue.Body = new CottageWars.DatabaseServiceReference.registerUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.email = email;
            return ((CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap)(this)).registerUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CottageWars.DatabaseServiceReference.updateBuildingResponse CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap.updateBuilding(CottageWars.DatabaseServiceReference.updateBuildingRequest request) {
            return base.Channel.updateBuilding(request);
        }
        
        public bool updateBuilding(string username, string building) {
            CottageWars.DatabaseServiceReference.updateBuildingRequest inValue = new CottageWars.DatabaseServiceReference.updateBuildingRequest();
            inValue.Body = new CottageWars.DatabaseServiceReference.updateBuildingRequestBody();
            inValue.Body.username = username;
            inValue.Body.building = building;
            CottageWars.DatabaseServiceReference.updateBuildingResponse retVal = ((CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap)(this)).updateBuilding(inValue);
            return retVal.Body.updateBuildingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.updateBuildingResponse> CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap.updateBuildingAsync(CottageWars.DatabaseServiceReference.updateBuildingRequest request) {
            return base.Channel.updateBuildingAsync(request);
        }
        
        public System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.updateBuildingResponse> updateBuildingAsync(string username, string building) {
            CottageWars.DatabaseServiceReference.updateBuildingRequest inValue = new CottageWars.DatabaseServiceReference.updateBuildingRequest();
            inValue.Body = new CottageWars.DatabaseServiceReference.updateBuildingRequestBody();
            inValue.Body.username = username;
            inValue.Body.building = building;
            return ((CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap)(this)).updateBuildingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CottageWars.DatabaseServiceReference.buildUnitsResponse CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap.buildUnits(CottageWars.DatabaseServiceReference.buildUnitsRequest request) {
            return base.Channel.buildUnits(request);
        }
        
        public bool buildUnits(string username, int gladiator, int brute, int infatry) {
            CottageWars.DatabaseServiceReference.buildUnitsRequest inValue = new CottageWars.DatabaseServiceReference.buildUnitsRequest();
            inValue.Body = new CottageWars.DatabaseServiceReference.buildUnitsRequestBody();
            inValue.Body.username = username;
            inValue.Body.gladiator = gladiator;
            inValue.Body.brute = brute;
            inValue.Body.infatry = infatry;
            CottageWars.DatabaseServiceReference.buildUnitsResponse retVal = ((CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap)(this)).buildUnits(inValue);
            return retVal.Body.buildUnitsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.buildUnitsResponse> CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap.buildUnitsAsync(CottageWars.DatabaseServiceReference.buildUnitsRequest request) {
            return base.Channel.buildUnitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.buildUnitsResponse> buildUnitsAsync(string username, int gladiator, int brute, int infatry) {
            CottageWars.DatabaseServiceReference.buildUnitsRequest inValue = new CottageWars.DatabaseServiceReference.buildUnitsRequest();
            inValue.Body = new CottageWars.DatabaseServiceReference.buildUnitsRequestBody();
            inValue.Body.username = username;
            inValue.Body.gladiator = gladiator;
            inValue.Body.brute = brute;
            inValue.Body.infatry = infatry;
            return ((CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap)(this)).buildUnitsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CottageWars.DatabaseServiceReference.getUnitsResponse CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap.getUnits(CottageWars.DatabaseServiceReference.getUnitsRequest request) {
            return base.Channel.getUnits(request);
        }
        
        public bool getUnits(string Username) {
            CottageWars.DatabaseServiceReference.getUnitsRequest inValue = new CottageWars.DatabaseServiceReference.getUnitsRequest();
            inValue.Body = new CottageWars.DatabaseServiceReference.getUnitsRequestBody();
            inValue.Body.Username = Username;
            CottageWars.DatabaseServiceReference.getUnitsResponse retVal = ((CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap)(this)).getUnits(inValue);
            return retVal.Body.getUnitsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.getUnitsResponse> CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap.getUnitsAsync(CottageWars.DatabaseServiceReference.getUnitsRequest request) {
            return base.Channel.getUnitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CottageWars.DatabaseServiceReference.getUnitsResponse> getUnitsAsync(string Username) {
            CottageWars.DatabaseServiceReference.getUnitsRequest inValue = new CottageWars.DatabaseServiceReference.getUnitsRequest();
            inValue.Body = new CottageWars.DatabaseServiceReference.getUnitsRequestBody();
            inValue.Body.Username = Username;
            return ((CottageWars.DatabaseServiceReference.DatabaseManagerServiceSoap)(this)).getUnitsAsync(inValue);
        }
    }
}
