//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CottageWars
{
    using System;
    using System.Collections.Generic;
    
    public partial class Units
    {
        public int Id { get; set; }
        public short Infatry { get; set; }
        public short Gladiator { get; set; }
        public short Brute { get; set; }
    
        public virtual User User { get; set; }
    }
}
